name = "news-pages"
main = "functions/api/stream.js"  # Path to your function script
compatibility_date = "2024-07-29"

[build]
command = ""  # No build command needed unless you're compiling code
directory = "functions/api"  # Directory where your function resides

[env.production]
# Specify any environment-specific settings here
